config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'dashboard#index'
  root "dashboard#argumentation"

  get '/logout', to: "dashboard#logout"

  get '/argumentation', to: "dashboard#argumentation", as: 'argumentation'
  post '/argumentation', to: "dashboard#argumentation"

  resources :argumentations, only: [ :index, :show, :create, :update]
  post '/destroyargumentation', to: "argumentations#destroyargumentation"
  get '/search', to: "argumentations#search"
  post '/search', to: "argumentations#search"

  get '/myargumentations', to: "argumentations#myargumentations"
  get '/sanitizepreview', to: "argumentations#sanitizepreview"

  post '/searchtitle', to: "argumentations#searchtitle"

  get '/getcomments', to: "argument_comments#getcomments"
  get '/getmycomments', to: "argument_comments#getmycomments"

  get '/getcurrentuser', to: "dashboard#get_current_user"

  resources :argument_comments
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index

  end

  def argumentation

  end

  def get_current_user
    @id = 0
    if current_user
      @id = current_user.id
    end
    respond_to do |format|
      format.json { render json: @id}
    end
  end

  def logout
    sign_out
    redirect_to root_path
  end
end

app/views/dashboard/argumentation.html.erb
<article ng-app="ArgumentationController">
  <div ng-view></div>
</article>

app/views/dashboard/index.html.erb
<header>
  <h1>
    Welcome to Prove Me Wrong
  </h1>
  <h2>
   App made by Sandro Räss
  </h2>
</header>
<section>
  <p>
    Philosophy for the win
  </p>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</section>

<%= link_to "To the overview", argumentation_url %><br>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>


<% if user_signed_in? %>
    <li>
      <%= link_to('Edit registration', edit_user_registration_path) %>
    </li>
<% else %>
    <li>
      <%= link_to('Register', new_user_registration_path)  %>
    </li>
<% end %>


<% if user_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    </li>
<% else %>
    <li>
      <%= link_to('Login', new_user_session_path)  %>
    </li>
<% end %>